# Site settings
title: Basecamp Insights
email: hello@basecampinsights.com
description: "Basecamp Insights, a design thinking platform for the enterprise.  Innovation begins here."
baseurl: ""
url: "http://basecampinsights.com" # for production
# url: "http://0.0.0.0:4000" # for staging

# Build settings
markdown: redcarpet
permalink: pretty
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
exclude: ["CNAME", "README.md"] # exclude files from site build

